### ISSUE TITLE
Documentation/README

### ISSUE THREAD

**Issue by xitep** [fede1024/rust-rdkafka#1]
This looks like a very promising library! Is there any chance to give it a README with some basic information, one shot example, and links to autogenerated documentation? May a link to the documentation provided by [docs.rs](https://docs.rs/) would suffice.

**Comment by fede1024** [comment]
Thanks! Yes the code is quite obscure (and low quality) at the moment, mainly because I'm doing quite a lot of experimentation and the API is changing all the time. The readme file really needs some basic information (dependencies, how to run the examples, how the library works etc.) I'll add it soon.

**Comment by xitep** [comment]
@fede1024 thank you for the update of the README.
