### ISSUE TITLE
Broken consumer is created instead of failure

### ISSUE THREAD

**Issue by tau3** [fede1024/rust-rdkafka#228]
Hello! 

I have a code to synchronously consume messages from a topic:
```rust
    let consumer: BaseConsumer = ClientConfig::new()
        .set("group.id", "some_group")
        .create()?;

    consumer
        .subscribe(&["some_topic"])?;

    for message in &consumer {
        println!("{:?}", message?);
    }
```
It's obviously broken because no `bootstrap.servers` are specified. I expected this to fail on `create`, but instead it stucks on cycle (probably waiting forever for a message).

**Comment by benesch** [comment]
Yeah, sorry, this is apparently by design. 🤷‍♂ librdkafka allows adding brokers dynamically, and apparently this behavior is desirable. Here's an upstream source: https://github.com/edenhill/librdkafka/issues/588. That talks about producers, not consumers, but I assume the same logic applies to consumers.

FWIW, it's quite possible you're getting an error or log message about the lack of brokers, via https://docs.rs/rdkafka/0.23.1/rdkafka/client/trait.ClientContext.html. That will log via `log::error!` by default, but if you don't have something like env_logger initialized, you won't see the message.

**Comment by tau3** [comment]
Thank you for quick reply!

I specifed `bootstrap.servers` and made a custom context (based on examples) that just prints everything to stdout but didn't receive any errors/messages.

```rust
struct CustomContext;

impl ClientContext for CustomContext {
    fn log(&self, level: RDKafkaLogLevel, fac: &str, log_message: &str) {
        println!("log: {} {}", fac, log_message);
    }

    fn stats(&self, statistics: Statistics) {
        println!("stats: {:?}", statistics)
    }

    fn error(&self, error: KafkaError, reason: &str) {
        println!("error: {} {}", error, reason)
    }
}

impl ConsumerContext for CustomContext {
    fn pre_rebalance(&self, rebalance: &Rebalance) {
        println!("Pre rebalance {:?}", rebalance);
    }

    fn post_rebalance(&self, rebalance: &Rebalance) {
        println!("Post rebalance {:?}", rebalance);
    }

    fn commit_callback(&self, result: KafkaResult<()>, _offsets: &TopicPartitionList) {
        println!("Committing offsets: {:?}", result);
    }
}

type CustomConsumer = BaseConsumer<CustomContext>;

fn main() -> KafkaResult<()> {
    let consumer: CustomConsumer = ClientConfig::new()
        .set("group.id", "some_group")
        .set("bootstrap.servers", "some_server")
        .create_with_context(CustomContext)?;

    consumer.subscribe(&["some_topic"])?;

    for message in &consumer {
        println!("{:?}", message?);
    }

    Ok(())
}
```

**Comment by tau3** [comment]
I was able to read logs after caches cleanup and rebuild. Looks like it's a broker compatibility issue.

**Comment by benesch** [comment]
Ok, great!
