### ISSUE TITLE
Example for async-std implementation

### ISSUE THREAD

**Issue by tsteenkamp** [fede1024/rust-rdkafka#352]
Hi,
any chance someone has the time to provide an example to implement async consumer/producer via async-std (and maybe async_trait needed as well)?

I just started with rust and it's really hard to understand what is going on in the smol example for using a different runtime than tokio.

Many thanks for any help!

**Comment by tsteenkamp** [comment]
This seems to work:
```
pub struct AsyncStdRuntime;

impl AsyncRuntime for AsyncStdRuntime {
    type Delay = Pin<Box<dyn std::future::Future<Output = ()> + Send + 'static>>;

    fn spawn<T>(task: T)
    where
        T: Future<Output = ()> + Send + 'static,
    {
        async {
            task::spawn(task).await;
        };
        ()
    }

    fn delay_for(duration: Duration) -> Self::Delay {
        Box::pin(task::sleep(duration))
    }
}
```
Although the async block causes a compiler warning.
Maybe someone with more experience can come up with a better solution.

**Comment by benesch** [comment]
Your attempt looks pretty good! The reason you're getting that warning is because you're awaiting the value in `spawn`, when you want to just fire-n-forget the task by dropping it. I'm adding an example in #355 that should clear this up. Feel free to follow up if you have any questions!

> I just started with rust and it's really hard to understand what is going on in the smol example for using a different runtime than tokio.

Yeah, getting started with Rust _and_ async/await _and_ rust-rdkafka all at once is no small feat. Happy to entertain suggestions to make things more clear to newcomers, but unfortunately there's just a bunch of inherent complexity. Glueing Rust's async/await ecosystem to librdkafka (a C library) is not quite seamless.
