### ISSUE TITLE
Batch Processing

### ISSUE THREAD

**Issue by vitruvvius** [fede1024/rust-rdkafka#402]
I understand the hesitation in adding to the publishing api an explicit batch processing fn (it already batches under the hood) - but it's unclear to me the purpose of not having this api in the consumer. We should remove complexity from the consumer. I note this after going through previous replies to the same feature request

**Comment by vitruvvius** [comment]
in fact, i see that rd_kafka_consume_batch is never called....

**Comment by benesch** [comment]
What benefit would it provide? Kafka is a streaming system. Most consumers want to read data as quickly as it arrives. If you want to wait to accumulate data into batches, you can do that downstream of rust-rdkafka. The API that's provided is strictly more general purpose than a batch-based API.

With some systems, reading batches can be more efficient than reading one at a time. But the underlying librdkafka library does not expose such an API, so there isn't an efficiency improvement to be had. 

One of the great things about exposing a `futures::Stream` is that it is automatically compatible with libraries like https://github.com/mre/futures-batch, which can easily add a batching API on top of any `Stream`.

**Comment by vitruvvius** [comment]
correct - Kafka is a streaming system. Kafka also has support for polling a batch w/ a max limit under the hood. one does not wait. it attempts to acquire a batch of size 1000, say, then the consumer operates on those 1000 objects. if there's not 1000 objects readily available, again, it does not wait. it returns immediately.

thanks for the note.

**Comment by vitruvvius** [comment]
Feel as though this should be re-opened

**Comment by benesch** [comment]
> there are alternatives that don't require one to reinvent the wheel every time, such as, including support!

Another way of looking at it, though, is that including a batch-based API in rust-rdkafka _is_ reinventing the wheel, as that sort of batching logic is already available in the futures-batch crate. 

Adding additional API surface is an additional maintenance burden. It's code that needs to be written, tested, and maintained across librdkafka version upgrades. So making the decision to add that API is not to be taken lightly. I don't think you've sufficiently justified your position here. What are these common situations you've found where you need to operate on batches rather than a single message at a time? How often is this occurring? What code are you currently writing today that is onerous? What is your proposed API that would simplify these situations? How many of these situations would these API be sufficient to cover?

I'd also be significantly more convinced in the face of benchmarks that demonstrate a sizeable performance delta between the current API and the proposed batch API.

**Comment by vitruvvius** [comment]
Anyone that operates w/ data at scale (>1M messages per minute) does batch processing on their streams.

**Comment by vitruvvius** [comment]
I think the last note in your paragraph

"I'd also be significantly more convinced in the face of benchmarks that demonstrate a sizeable performance delta between the current API and the proposed batch API."

is the most compelling argument from your point of view. you are declaring that the current API can produce the same performance at the same cost of resources. and since i will not be undertaking testing that claim, and this was a request not an assertion, hopefully this thread can be a good reference for future inquiries.

final note, since im an advocate for precision, on the "reinventing the wheel" comment - this library quite literally is the definition of reinventing the wheel of librdkafka.

**Comment by benesch** [comment]
> Anyone that operates w/ data at scale (>1M messages per minute) does batch processing on their streams.

I'm very skeptical of absolute claims like this. A simple transformation of a stream can easily process messages one by one and achieve processing rates of 1MM.

> you are declaring that the current API can produce the same performance at the same cost of resources.

I'm saying we don't know! If it's the batch API yields only a small performance gain (<5%, say), it's a hard call to say whether it's worth the increased API surface. If it's a big performance gain it's much more compelling.

> and since i will not be undertaking testing that claim, and this was a request not an assertion

This gets at the heart of my contention here. You've not provided either reproducible or anecdotal evidence that adding this API would be sufficiently justified. If you or someone else wants to provide that evidence, I'd be happy to reconsider.

> final note, since im an advocate for precision, on the "reinventing the wheel" comment - this library quite literally is the definition of reinventing the wheel of librdkafka.

As I think you've realized, since you deleted this part of your comment: this is incorrect. This library provides Rust bindings on _top_ of librdkafka. It does not reimplement anything that already exists in librdkafka.

**Comment by vitruvvius** [comment]
you must not care about persistence of data if you claim to operate on > 1M messages per minute one by one. i removed the last part in order to resolve this issue & stop receiving notifications. not going to get in a word fight - bindings are reinventing the wheel by definition.

**Comment by vitruvvius** [comment]
i thank the team for the hard work to make this api.

**Comment by benesch** [comment]
> you must not care about persistence of data if you claim to operate on > 1M messages per minute one by one.

I'm afraid that's not true. Materialize can consume, transform, and produce back to a Kafka topic 1MM messages/minute without batch processing.

Again, I'm happy to entertain evidence that would justify a batch processing API! Benchmarks are the most compelling evidence, but examples of painful code that you find yourself repeatedly writing downstream of rust-rdkafka are also compelling.

> not going to get in a word fight - bindings are reinventing the wheel by definition.

I just can't make sense of this argument. Are you perhaps confused about what bindings are? If you want to use Kafka from Rust, you have two options: write bindings for an existing Kafka library that's written in another language, or write a new Kafka library in pure Rust. The former is what this library does, and as a result it's very little code. The latter is what could be called "reinventing the wheel", because you have to reimplement all of librdkafka in Rust.

**Comment by vitruvvius** [comment]
reinvent the wheel - "to duplicate a basic method that has already previously been created or optimized by others"

you must be confused on bindings, since this library is separate from rdkafka-sys. and, if this was a library that did automatically generate bindings, you'd have one for a batch api out of the box. and, even if it were the binding library, it fits that definition.

it would be great to turn off comments on this - as we've discussed, i have no plans on an extensive benchmark that analyzes low-level perf, flame graphs, and any other system stats that come to light.

Thanks.

**Comment by benesch** [comment]
> you must be confused on bindings, since this library is separate from rdkafka-sys. and, if this were the same underlying binding library that automatically generates bindings, you'd have one for a batch api out of the box. and, even if it were the binding library, it fits that definition.

Both crates are part of this repository. Indeed, `rdkafka-sys` exposes the [`rd_kafka_consume_batch`](https://docs.rs/rdkafka-sys/latest/rdkafka_sys/bindings/fn.rd_kafka_consume_batch.html) API, but calling it correctly from Rust is difficult and requires `unsafe` code. It doesn't reinvent anything: it provides access to the existing C API from Rust code, which is not possible without the binding.

> it would be great to turn off comments on this - as we've discussed, i have no plans on an extensive benchmark that analyzes low-level perf, flame graphs, and any other system stats that come to light.

I'm going to leave comments open, in case someone else wants to come along and provide evidence that justifies adding the batch API.

**Comment by kirit0s** [comment]
IO operations without batch will be slow. Kafka use batch under the hood. I want to get 1mb of data and do 1 request to database, instead of ~200k requests (much much slower). All the clients I've seen has batch api (even kafka-rust). Why break up a batch and then try to merge it back together with other libs?
