### ISSUE TITLE
mention how to statically link in the docs?

### ISSUE THREAD

**Issue by Roguelazer** [fede1024/rust-rdkafka#52]
The change to dynamically link librdkafka caused me some issues today, and it took me a while of reading through `pkg-config-rs` documentation to figure out that if I set the environment variable `RDKAFKA_NO_PKG_CONFIG=1` before running `cargo build`, `rdkafka-sys` would build the embedded static copy.

This may be worth mentioning somewhere in the rust-rdkafka documentation?

**Comment by fede1024** [comment]
First of all, sorry for the pain caused. Just to make sure I understand your use case correctly: you have librdkafka installed in your system, so rdkafka-sys is now linking dynamically to it instead of statically, and you want a way to force static linking instead. Is this correct?

The way it currently works is unintuitive, since the static vs dynamic will depend on the state of the machine where compilation occurs. I think it would be better to have static compilation by default, and have opt-in dynamic using a feature.

**Comment by Roguelazer** [comment]
Specifically: I have librdkafka installed on the system that's building the binary, but not on the systems it's being deployed to, and was being lazy and not properly checking `ldd`.

Even if static isn't the default, it would be nice to be able to control this with a feature (e.g., in `rusqlite` the "bundled" feature forces static linkage).

**Comment by fede1024** [comment]
The master branch will now always use static linking, independently of what's installed on the system. The new `dynamic_linking` feature will enable dynamic linking, and it will fail if the library is not installed.

**Comment by Roguelazer** [comment]
Thanks!
