### ISSUE TITLE
async batching support

### ISSUE THREAD

**Issue by Kane-Sendgrid** [fede1024/rust-rdkafka#59]
It seems it doesn't support async batching like java producer?
To make it work API probably has to be changed/extended, are you thinking about adding it?

**Comment by fede1024** [comment]
The batching is done by the underlying librdkafka library. The producer will not send the messages straight away, instead they will be batched according to the configuration and then sent as a single request (see `queue.buffering.max.ms`, `queue.buffering.max.kbytes` and `queue.buffering.max.messages` in the [librdkafka configuration](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md)). This should be equivalent to what the Java producer does.

If what you mean is having a send method that can handle multiple messages at the same time, it might be supported in the future. However the performance improvement, compared to simply sending the messages in a loop, should be minimal, so it's currently a low priority change.

**Comment by Kane-Sendgrid** [comment]
@fede1024 yes, I was talking about the batching you described, awesome if it works out of the box.
Can you share some details how it works under the hood? Does librdkafka manage connections to kafka and how did you integrate it with tokio core loop. If buffer is full will try_send return an error or block?

**Comment by fede1024** [comment]
librdkafka has its own event loop and connection management. The high level producer and consumer in rust-rdkafka provide async interfaces in terms of futures and streams. Tokio is not a dependency for rust-rdkafka, and there is no event loop in the rust library. The library, however, provides an interface based on the abstraction provided by the `futures` crate, making it easy to integrate with Tokio.

The send function will not block and it will return a `QueueFull` error instead, in both the low level and high level producers. I'd like to improve the high level producer, so that the user won't have to handle this error unless she explicitly want to. However that's not implemented yet.

I hope this gives some clarity on your questions. I'll add more general documentation to the producer and consumer modules. Let me know if you have any other question.

**Comment by Kane-Sendgrid** [comment]
Thanks, this answers all questions I had, I'll close it now. 
P.S. Did you look at sarama's producer (https://github.com/Shopify/sarama/wiki/Producer-implementation)?

**Comment by fede1024** [comment]
I haven't looked in depth. Thank you for the link, I'll have a look.
