### ISSUE TITLE
Fatal error: Local: Inconsistent state on FutureProducer with enable.idempotence = true

### ISSUE THREAD

**Issue by lurqui21** [fede1024/rust-rdkafka#630]
Hi, I receive this error:
```
Fatal error: Local: Inconsistent state: Unable to reconstruct MessageSet (currently with 5 message(s)) with msgid range 1..15: last message added has msgid 5: unable to guarantee consistency
```
whenever I turn on `enable.idempotence=true` when using FutureProducer or ThreadedProducer.

My application is an actix web server that simply sends input jsons into kafka. On dev/local environment idempotence with low load works, however on prod with around 5k msg/sec I begin to receive this error, afterwards no more messages are being received by kafka.

When `enable.idempotence=false` the application works just fine.

**Comment by whyjp** [comment]
Hi, I also directly use librdkafka with C++, and
recently I've been using Vector: Rust rdkafka as well.
I've also experienced this issue, and
I believe this bug was fixed in the recent rdkafka 2.10 version.
https://github.com/confluentinc/librdkafka/pull/4750/commits/f87d854725ddf9dcdb553f0f0b231dff87f26aed
Based on the fix content and the message,
it seems highly likely that this was a bug.
So I think Rust rdkafka also needs a release that includes this fixed version.
Of course, besides the above issue, when a fatal error occurs,
recovery is necessary, but
the problem is:
If you want to reset=reinitialize the producer and create it again for producing when a fatal error occurs,
preserving > reprocessing the existing buffer is essential.
For this part, I think it needs to be manually modified by the user rather than implemented in Rust-rdkafka.
