### ISSUE TITLE
How to consume two topics with different configurations

### ISSUE THREAD

**Issue by pimeys** [fede1024/rust-rdkafka#97]
I'm trying to do the following:

```rust
let consumer: StreamConsumer = ClientConfig::new()
    .set("group.id", &self.group_id)
    .set("bootstrap.servers", &self.brokers)
    .set("enable.auto.commit", "true")
    .set("auto.offset.reset", "latest")
    .set("enable.partition.eof", "false")
    .create()
    .expect("Consumer creation failed");

let mut partitions = TopicPartitionList::new();
partitions.add_partition_offset(&self.config_topic, 0, Offset::Beginning);
consumer.subscribe(&[&self.input_topic]).expect("Can't subscribe to specified topics");
consumer.assign(&partitions).expect("Can't subscribe to specified topics");
```

So in this case we subscribe to two topics, the other is a compact topic with configuration that's read always from beginning when you start the consumer, then additionally modifying the consumer state whenever there's new events in the config topic.

The other is a topic with lots of partitions, we must never consume these items more than once and we want to have automatic partition assignment. My code over here doesn't seem to do what I expect. If I keep it like so, I never get any items from the config topic, but the input topic data is consumed and handled. If I remove the `.subscribe` to input topic, the consumer consumes the config topic from beginning as I expect.

How to do this properly? It's handy to hold the mutable consumer state in the same loop, but it seems you cannot subscribe and assign partitions like I did above.

**Comment by benesch** [comment]
Right, so assigning explicit partitions will blow away whatever subscriptions you've requested. What you can do instead is subscribe to both topics, and then use a rebalance callback to adjust the partition on the config topic to 0. The librdkafka has docs on how to do this for C/C++: https://github.com/edenhill/librdkafka/wiki/Manually-setting-the-consumer-start-offset.

In Rust, you'd override [`ConsumerContext::rebalance`](https://docs.rs/rdkafka/0.21.0/rdkafka/consumer/trait.ConsumerContext.html#method.rebalance) and then adapt the code to work with the [`TopicPartitionList`](https://docs.rs/rdkafka/0.21.0/rdkafka/topic_partition_list/struct.TopicPartitionList.html) object.

Alternatively, I think you could just set the `auto.offset.reset` to `earliest` for the config topic (when you create it). Then you could simply subscribe to both topics. This would require you to disable auto commit, though, and then manually commit offsets for the input topic (but not the config topic).

I'm going to close this out because it's unlikely that you're still interested in the answer to this one year later. Apologies!
